language: android

# setup
android:
    components:
        - tools
        - platform-tools
        - build-tools-22.0.1
        - extra-android-m2repository
        - android-22

    licenses:
        - '.+'

# testing env
jdk: oraclejdk8

env:
    - ANDROID_TARGET=22

# ignore
branches:
    except:
        - gh-pages

# lifecycle
before_install:
    - chmod +x gradlew

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .gradle/caches/
        - .gradle/wrapper/

notifications:
    slack: nctuimf:fso8u4u2iMWtFrWwrkOdBXL9

